export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAIL = "CREATE_TODO_FAIL";
export const CREATE_TODO_RESET = "CREATE_TODO_RESET";

export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";
export const UPDATE_TODO_RESET = "UPDATE_TODO_RESET";

export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";
export const DELETE_TODO_RESET = "DELETE_TODO_RESET";

export const GETBYID_TODO_REQUEST = "GETBYID_TODO_REQUEST";
export const GETBYID_TODO_SUCCESS = "GETBYID_TODO_SUCCESS";
export const GETBYID_TODO_FAIL = "GETBYID_TODO_FAIL";
export const GETBYID_TODO_RESET = "GETBYID_TODO_RESET";

export const GET_ALL_TODO_REQUEST = "ADMIN_GETBYALL_TODO_REQUEST";
export const GET_ALL_TODO_SUCCESS = "ADMIN_GETBYALL_TODO_SUCCESS";
export const GET_ALL_TODO_FAIL = "ADMIN_GETBYALL_TODO_FAIL";
export const GET_ALL_TODO_RESET = "ADMIN_GETBYALL_TODO_RESET";
